### ISSUE TITLE
SVGs do not render in Documentation

### ISSUE THREAD

**Issue by reiner-dolp** [1602/elm-feather#10]
Since the 0.19 update, the SVG images in the package docs do no longer render. Using a link to an svg using the image `![image](url)` syntax would probably work.

![image](https://user-images.githubusercontent.com/770508/44949393-9702b380-ae30-11e8-9371-f76b92ab147c.png)

**Comment by 1602** [comment]
Solution with `![image](url)` worked, thank you for suggestion.
