### ISSUE TITLE
Coordination with arnaud/elm-feather?

### ISSUE THREAD

**Issue by mpizenberg** [1602/elm-feather#5]
Hey again, I was just randomly browsing the elm packages website and stumbled upon [arnaud/elm-feather] which seems to predate yours, but was not as well advertized I guess ;)

It might be a good idea to coordinate with @arnaud to unify the packages so that there is an obvious option when 0.19 arrives.

Cheers

[arnaud/elm-feather]: http://package.elm-lang.org/packages/arnau/elm-feather/latest

**Comment by 1602** [comment]
Thanks, I completely missed this package when created mine, feel sorry about that. So, let's coordinate with @arnaud.

**Comment by 1602** [comment]
Let's continue discussion in https://github.com/arnau/elm-feather/issues/1
